name:                RetroPE
version:             0.1.0.0
github:              "JacquesCarette/Theseus"
license:             BSD3
author:              ["Jacques Carette", "Amr Sabry"]
maintainer:          ["carette@mcmaster.ca", "sabry@indiana.edu"]
copyright:           "2022 Jacques Carette and Amr Sabry"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/RetroPE#readme>

dependencies:
- base 
- vector
- QuickCheck
- containers
- assert
- integer-gmp
- lens
- random >= 1.2.1

library:
  source-dirs:
    src
  when:
    - condition: false
      other-modules: Paths_RetroPE


executables:
  RetroPE-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RetroPE

tests:
  RetroPE-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RetroPE
